<!DOCTYPE html>
<html>
<head>
   <center>
    <title>Pagina de curioso ☝️🤓</title>
        <style>
                body {
                            background-color: black;
                                        color: white;
                                                    padding: 20px;
                                                                font-family: Arial, sans-serif;
                                                                        }
                                                                            </style>
                                                                            </head>
                                                                            <body>
                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        <center>
                                                                                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                                                                                            <a class="neon-bt" href="http://t.me/teddy_do_7">

                                                                                                                                                                                                                                                                                                                                                                                                  <span></span>

                                                                                                                                                                                                                                                                                                                                                                                                        <span></span>

                                                                                                                                                                                                                                                                                                                                                                                                              <span></span>

                                                                                                                                                                                                                                                                                                                                                                                                                    <span></span>

                                                                                                                                                                                                                                                                                                                                                                                                                          CODER

                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                   <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt { position: relative; display: inline-block; padding: 10px 20px; color: #03e9f4; font-size: 30px; text-decoration: none; text-transform: uppercase; overflow: hidden; transition: 0.2s; margin-top: 40px; letter-spacing: 4px; margin-left: 10px }

                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt:hover { background: #03e9f4; color: #fff; border-radius: 5px; box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4; }

                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt span { position: absolute; display: block; }

                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt span:nth-child(1) { top: 0; left: -100%; width: 100%; height: 2px; background: linear-gradient(90deg, transparent, #03e9f4); animation: btn-anim1 1s linear infinite; }

                                                                                                                                                                                                                                                                                                                                                                                                                                   @keyframes btn-anim1 { 0% { left: -100%; } 50%,100% { left: 100%; } }

                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt span:nth-child(2) { top: -100%; right: 0; width: 2px; height: 100%; background: linear-gradient(180deg, transparent, #03e9f4); animation: btn-anim2 1s linear infinite; animation-delay: .25s }

                                                                                                                                                                                                                                                                                                                                                                                                                                   @keyframes btn-anim2 { 0% { top: -100%; } 50%,100% { top: 100%; } }

                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt span:nth-child(3) { bottom: 0; right: -100%; width: 100%; height: 2px; background: linear-gradient(270deg, transparent, #03e9f4); animation: btn-anim3 1s linear infinite; animation-delay: .5s }

                                                                                                                                                                                                                                                                                                                                                                                                                                   @keyframes btn-anim3 { 0% { right: -100%; } 50%,100% { right: 100%; } }

                                                                                                                                                                                                                                                                                                                                                                                                                                   .neon-bt span:nth-child(4) { bottom: -100%; left: 0; width: 2px; height: 100%; background: linear-gradient(360deg, transparent, #03e9f4); animation: btn-anim4 1s linear infinite; animation-delay: .75s }

                                                                                                                                                                                                                                                                                                                                                                                                                                   @keyframes btn-anim4 { 0% { bottom: -100%; } 50%,100% { bottom: 100%; } } 	
                                                                                                                                                                                                                                                                                                                                                                                                                                    </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                     <center>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <h1>ACESSO PROIBIDO<h1>
                                                                                                                                       <h2> Vaza daqui pnc</h2>                                                                                                                                                                                                                                                                                            </center>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <!DOCTYPE html>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <html>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <head>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <title>Pagina de intrusos</title>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      body {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background-color: black;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: white;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              form {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          margin-top: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          button {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 10px 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background-color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: black;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </html>